name: stac-fastapi-elasticsearch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - features/**

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:

      elasticsearch_8_svc:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        env:
          cluster.name: stac-cluster
          node.name: es01
          network.host: 0.0.0.0
          transport.host: 0.0.0.0
          discovery.type: single-node
          http.port: 9200
          xpack.license.self_generated.type: basic
          xpack.security.enabled: false
          xpack.security.transport.ssl.enabled: false
          ES_JAVA_OPTS: -Xms512m -Xmx1g
        ports:
          - 9200:9200

      elasticsearch_7_svc:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
        env:
          cluster.name: stac-cluster
          node.name: es01
          network.host: 0.0.0.0
          transport.host: 0.0.0.0
          discovery.type: single-node
          http.port: 9400
          xpack.license.self_generated.type: basic
          xpack.security.enabled: false
          xpack.security.transport.ssl.enabled: false
          ES_JAVA_OPTS: -Xms512m -Xmx1g
        ports:
          - 9400:9400
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11"]

    name: Python ${{ matrix.python-version }} testing

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint code
        uses: pre-commit/action@v3.0.0

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install elasticsearch stac-fastapi
        run: |
          pip install ./stac_fastapi/elasticsearch[dev,server]

      - name: Run test suite against Elasticsearch 7.x
        run: |
          cd stac_fastapi/elastic_search && pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing
          ES_PORT: 9200
          ES_HOST: 172.17.0.1
          ES_USE_SSL: false
          ES_VERIFY_CERTS: false

      - name: Run test suite against Elasticsearch 8.x
        run: |
          cd stac_fastapi/elastic_search && pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing
          ES_PORT: 9400
          ES_HOST: 172.17.0.1
          ES_USE_SSL: false
          ES_VERIFY_CERTS: false