name: stac-fastapi-elasticsearch
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:

      elasticsearch_7_svc:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
        env:
          node.name: es01
          cluster.name: stac-cluster
          discovery.type: single-node
          network.host: 0.0.0.0
          http.port: 9200
          ES_JAVA_OPTS: -Xms512m -Xmx512m
        ports:
          - 9200:9200

#      elasticsearch_8_svc:
#        image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
#        env:
#          node.name: es01
#          cluster.name: stac-cluster
#          discovery.type: single-node
#          network.host: 0.0.0.0
#          http.port: 9200
#          ES_JAVA_OPTS: -Xms512m -Xmx512m
#        ports:
#          - 9200:9200

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Lint code
        uses: pre-commit/action@v2.0.0

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install elasticsearch stac-fastapi
        run: |
          pip install ./stac_fastapi/elasticsearch[dev,server]

      - name: Run test suite against Elasticsearch 7.x
        run: |
          cd stac_fastapi/elasticsearch && pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing
          ES_USER: dev
          ES_PASS: stac
          ES_PORT: 9200
          ES_HOST: 172.17.0.1
#
#      - name: Run test suite against Elasticsearch 8.x
#        run: |
#          cd stac_fastapi/elasticsearch && pipenv run pytest -svvv
#        env:
#          ENVIRONMENT: testing
#          ES_USER: dev
#          ES_PASS: stac
#          ES_PORT: 9400
#          ES_HOST: 172.17.0.1